apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: webui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: coastlinesss/webui:latest
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: webui
